@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzQ0MTYxMjh9.PRpfeEBq3tKwZ15WxrjQLuV69PVx_dbGVnoEhP9Tsgg
@host = http://localhost:3000

### Products index
GET {{host}}/products?category=Humor

### Create Product

POST {{host}}/products
Content-Type: application/json

{
  "name": "frank",
  "price": -30
}

### Products show

GET {{host}}/products/1

### Products update

PATCH {{host}}/products/6
Content-Type: application/json

{
  "price": 35,
  "inventory": 39
}

### Products destroy

DELETE {{host}}/products/5


### Users create (signup)
POST {{host}}/users
Content-Type: application/json

  {
    "name": "God Mod",
    "email": "mod@test.com",
    "password": "password",
    "password_confirmation": "password",
    "admin": true
  }

### Sessions create (login)
POST {{host}}/sessions
Content-Type: application/json

  {
    "email": "bigal@test.com",
    "password": "password"
  }

### Order create
POST {{host}}/orders
Content-Type: application/json
Authorization: Bearer {{jwt}}


{
    "product_id": 1,
    "quantity": 3
}

### Orders index
GET {{host}}/orders
Authorization: Bearer {{jwt}}

### Orders show
GET {{host}}/orders/2
Authorization: Bearer {{jwt}}


### Carted Products create
POST {{host}}/carted_products
Content-Type: application/json
Authorization: Bearer {{jwt}}

{ 
  "product_id": 1,  
  "quantity": 5
}