@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzE2NDE5NDl9.RZVzFSNsA_DnIsoYK-LAxGEUeX7rpQCwNnhHhFZ1Fs0

### Products index
GET http://127.0.0.1:3000/products?category=Humor

### Create Product

POST http://127.0.0.1:3000/products
Content-Type: application/json

{
  "name": "frank",
  "price": -30
}

### Products show

GET http://127.0.0.1:3000/products/1

### Products update

PATCH http://127.0.0.1:3000/products/6
Content-Type: application/json

{
  "price": 35,
  "inventory": 30
}

### Products destroy

DELETE http://127.0.0.1:3000/products/5


### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

  {
    "name": "God Mod",
    "email": "mod@test.com",
    "password": "password",
    "password_confirmation": "password",
    "admin": true
  }

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

  {
    "email": "bigal@test.com",
    "password": "password"
  }

### Order create
POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer {{jwt}}


{
    "product_id": 1,
    "quantity": 3
}

### Orders index
GET http://localhost:3000/orders
Authorization: Bearer {{jwt}}

### Orders show
GET http://localhost:3000/orders/2
Authorization: Bearer {{jwt}}


### Carted Products create
POST http://localhost:3000/carted_products
Content-Type: application/json

{ 
  "product_id": 1, 
  "user_id": 3, 
  "quantity": 5, 
  "status": "ordered", 
  "order_id": 3
}